### ISSUE TITLE
KOS_DEBUG level 2 or enabling KM_DBG_VERBOSE hang the DC

### ISSUE THREAD

**Issue by gyrovorbis** [KallistiOS/KallistiOS#290] opened 2023-09-03 05:20 UTC
This is a very low priority issue which impacts the power-user build configuration variables within `/kos/include/kos/opts.h`, but I still want to document this so it can eventually get fixed.

When KOS_DEBUG level 2 (or greater) is enabled, `KM_DBG_VERBOSE` becomes enabled (or it can be enabled directly), this enables a bunch of additional `printf()` calls all over `/kos/kernel/libc/koslib/malloc.c`. Currently with these enabled, the DC immediately hangs without so much as printing the regular KOS banner as soon as the application launches.

Creating a dummy macro to replace `printf()` with a NOP fixes the issue. So does changing the log to go to the framebuffer; however, going to the regular debug log still crashes... 

My theory is that these forms of logging are requiring internal buffer allocations which are calling into `malloc()` which are recursively calling back into the log functions, which call back into `malloc()`, etc... Not sure how this worked previously, but if the logging mechanism itself requires an allocation, we have to find a different mechanism for logging allocation debug messages.

**Comment by gyrovorbis** [comment] 2023-09-16 03:00
NOTE TO SELF: I was tracing through `printf()` today, and MOST DEFINITELY it's calling `malloc()` in there all over the place for buffering. I'm not so sure about the `dgblog()` path, but that definitely explains the initial `printf()`-based crashing...

**Comment by andressbarajas** [comment] 2023-12-09 03:57
@gyrovorbis Hey!  I remember reading that you were redoing how printf stuff was handled in the backend because how it was allocating buffers/slowness.  You think you killed this issue in that branch ?

**Comment by gyrovorbis** [comment] 2023-12-28 09:56
> t

Actually... good call. It's possible that this is only present when using buffering... because why else would it need to allocate? I'll test it out and report back!

**Comment by QuzarDC** [comment] 2024-06-01 01:05
This should be fixed, the `KM_DBG_VERBOSE` case at least, via #599. 

Without knowing *when* it broke, it's difficult to tell exactly the cause, but yes it basically was that the existing debug logging was requiring malloc. printf, for sure, but even going to dbglog using vsnprintf wasn't safe. While these shouldn't *require* mallocing, they, and va_args functions generally, do not guarantee that. I presume that either it had last been used with a homespun malloc-less printf, or that antique versions of newlib may have just avoided the issue somehow. But I can't see how this would have worked anytime in the last decade or so as I was able to replicate this (and its fix) in the gcc 9.3.0 legacy toolchain.

**Closed** 2024-06-05 02:51 UTC
Labels: bug
