### ISSUE TITLE
cpp/modplug_test prints garbage to console

### ISSUE THREAD

**Issue by darcagn** [KallistiOS/KallistiOS#261] opened 2023-08-09 19:05 UTC
Tested on GCC 9.3.0 and 13.2.0

modplug_test seems to work fine, but prints garbage to console.

Run once:
![Screenshot_20230730_201425](https://github.com/KallistiOS/KallistiOS/assets/5105103/4a2feddf-a3f4-4ed2-8bed-8d13897e373e)

Run twice:
![Screenshot_20230730_201459](https://github.com/KallistiOS/KallistiOS/assets/5105103/26714405-e017-49fa-a930-ce35cfce766b)

**Comment by gyrovorbis** [comment] 2023-09-03 07:00
Hey, dude... So I repro'd it immediately, then screwed around and suddenly could never see the problem again...

What I'm starting to wonder is if you and I might've gone from like GCC13.1.0 or something to GCC13.2.0 and rebuilt KOS but maybe not kos-ports? I definitely did that and forgot to rebuild kos-ports... Then while I was troubleshooting I uninstalled the port and reinstalled it, and now I can't reproduce the issue anymore...

This is C++ so it might be some ABI change in the stdlib or some crap like that?

**Comment by darcagn** [comment] 2023-09-03 19:49
I'm pretty sure I was rebuilding all of kos + kos-ports + example when swapping between tests (and between 9.3.0 and 13.2.0 tests) but I'll check again on this one soon.

**Comment by andressbarajas** [comment] 2023-12-10 01:55
@darcagn Im not seeing this one anymore:
![Screen Shot 2023-12-09 at 5 54 33 PM](https://github.com/KallistiOS/KallistiOS/assets/1459288/bc682df0-f555-4fc8-aa09-a03b76632a74)
When you have time, give it another test.

**Comment by gyrovorbis** [comment] 2023-12-21 05:34
Closing this as resolved. If it still exists, we can reopen.

**Closed by gyrovorbis** 2023-12-21 05:34 UTC
Labels: bug
