### ISSUE TITLE
Unable to build KallistiOS on GCC 4.x since LTO enabled

### ISSUE THREAD

**Issue by sizious** [KallistiOS/KallistiOS#156] opened 2023-04-20 22:01 UTC
**It’s now impossible to build KallistiOS using GCC 4.x since LTO (Link Time Optimization) is enabled.**

Some exports aren't properly defined, as shown [here](https://github.com/cepawiel/dreamcast-toolchain-containers/actions/runs/4598237777/jobs/8122028216#step:9:621). As explained by @pcercuei:

> `fdopen()` is in `stdio.h` and needs `_POSIX_C_SOURCE` to be defined to POSIX `2001` minimum. The generated code validates those conditions but we need to fix [genexports](https://github.com/KallistiOS/KallistiOS/tree/master/utils/genexports).

**Comment by pcercuei** [comment] 2023-04-22 17:34
genexports works fine. The problem is that this won't compile on the GCC4 toolchain:
```
#define _POSIX_C_SOURCE 200809
#include <stdio.h>

int main(void) {
    fdopen(0, NULL);
    return 0;
}
```

**Comment by gyrovorbis** [comment] 2023-04-23 20:09
I've opened a PR addressing this issue here: https://github.com/KallistiOS/KallistiOS/pull/159

**Comment by gyrovorbis** [comment] 2023-04-24 03:34
Should be fixed now, Crabby just approved my PR.

**Closed by gyrovorbis** 2023-04-24 03:34 UTC
Labels: bug, toolchain
